### ISSUE TITLE
Runtime error on large files for RDS#describe_db_log_files

### ISSUE THREAD

**Issue by bbergstrom** [aws/aws-sdk-core-ruby#190]
I think it happens on log files larger than 10mb.

```
/Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/text.rb:398:in `block in unnormalize': entity expansion has grown too large (RuntimeError)
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/text.rb:395:in `gsub'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/text.rb:395:in `unnormalize'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/text.rb:252:in `value'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:452:in `text'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:433:in `has_text?'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:57:in `merge_texts!'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:46:in `collapse'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:31:in `merge_element!'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `block in collapse'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:902:in `block in each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:902:in `each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:393:in `each_element'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `collapse'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:31:in `merge_element!'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `block in collapse'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:902:in `block in each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:902:in `each'
	from /Users/brianbergstrom/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rexml/element.rb:393:in `each_element'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `collapse'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:31:in `merge_element!'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:16:in `parse'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/multi_xml-0.5.5/lib/multi_xml.rb:138:in `parse'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/aws-sdk-core/xml/parser.rb:18:in `parse'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/aws-sdk-core/query/handler.rb:36:in `parse_xml'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/aws-sdk-core/query/handler.rb:13:in `block in call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/response.rb:43:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/response.rb:43:in `block in on'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/http/response.rb:135:in `block in on_success'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/http/response.rb:162:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/http/response.rb:162:in `block in listener'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/http/response.rb:126:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/http/response.rb:126:in `on_done'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/http/response.rb:133:in `on_success'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/response.rb:42:in `on'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/response.rb:51:in `on_success'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/aws-sdk-core/query/handler.rb:11:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/plugins/endpoint.rb:35:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/plugins/param_validation.rb:22:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/brianbergstrom/.rvm/gems/ruby-2.1.2@rds-pgbadger/gems/aws-sdk-core-2.0.17/lib/seahorse/client/base.rb:215:in `block (2 levels) in define_operation_methods'
```

**Comment by trevorrowe** [comment]
This error is being raised by REXML. Could you attempt to reproduce this error with one of the other supported XML parsers? The AWS SDK for Ruby uses the `multi_xml` gem, so simply requiring another XML parser, such as Ox (recommended) or nokogiri should bypass REXML.

```bash
$ gem install ox
```

```ruby
require 'ox'
require 'aws-sdk-core'

# your code here
```

**Comment by bbergstrom** [comment]
Using `ox` resolves the issue.  Thanks!

**Comment by trevorrowe** [comment]
Closing this as a non-issue for the SDK.
